language: python

sudo: true

branches:
  only:
    - master

python:
  # We don't actually use the Travis Python, but this keeps it organized.
  - "2.7"
  - "3.4"
  - "3.5"

install:
  - sudo apt-get update
  - sudo apt-get install -y libfreetype6-dev libfontconfig1-dev
  - if [[ "$TRAVIS_PYTHON_VERSION" == "2.7" ]]; then
      wget https://repo.continuum.io/miniconda/Miniconda2-latest-Linux-x86_64.sh -O miniconda.sh;
    else
      wget https://repo.continuum.io/miniconda/Miniconda3-latest-Linux-x86_64.sh -O miniconda.sh;
    fi
  - bash miniconda.sh -b -p $HOME/miniconda
  - export PATH="$HOME/miniconda/bin:$PATH"
  - hash -r
  - conda config --set always_yes yes --set changeps1 no
  - conda update --yes --quiet conda
  - conda install -n root conda conda-env anaconda-client
  - conda info -a
  - conda create -n nb_conda_kernels python=$TRAVIS_PYTHON_VERSION
  - conda env update
  - source activate nb_conda_kernels
  - pip install python-coveralls
  - npm install

script:
  - conda info -a
  - python setup.py develop
  - python -m nb_conda_kernels.install --enable --prefix="${CONDA_PREFIX}"
  - npm run test

after_success:
  - coveralls
