# Build only the master branch, tagged commits, and pull requests
branches:
  only:
    - master
    - /\d+\.\d+.*/
# Don't run the (redundant) branch build with a pull request
skip_branch_with_pr: true

environment:
  PYTHONUNBUFFERED: 1
  PYTHONIOENCODING: utf-8
  PYTHONLEGACYWINDOWSSTDIO: 1
  MINICONDA: C:\\Miniconda3-x64
  GITHUB_TOKEN:
    secure: FD+yykAWTe1d4HOLF23TkNhSnVeOyc213tkRfJxKaXbI7W89Jp9+6X54w8RPfLlW
  ANACONDA_TOKEN:
    secure: ARz+fIEDJ03ENwXTyuy0pkzmxddWXFc+pN9+mwBcCnT7ytqlQ/ojcnH3gYsLp9TB
  matrix:
    - PYTHON_VERSION: 3.7
    - PYTHON_VERSION: 3.6
    - PYTHON_VERSION: 3.5
    - PYTHON_VERSION: 2.7

init:
    - ps: Write-host $env:GITHUB_TOKEN

install:
    - mkdir C:\Users\appveyor\.conda
    - call %MINICONDA%\Scripts\conda.exe install conda --yes
    - call %MINICONDA%\Scripts\activate.bat
    - conda config --set always_yes yes --set changeps1 no --set safety_checks disabled
    - conda install -v conda-verify conda-build ipykernel anaconda-client
    # We need to create additional environments to fully test the logic,
    # including an R kernel, a Python kernel, and environment names with at
    # least one non-ASCII character and one space. We also need one environment
    # installed in a non-default environment location. Because AppVeyor is
    # difficult to work with for non-ASCII content we're using env files.
    - conda env create -f conda-recipe\testenv1.yaml -p %USERPROFILE%\.conda\envs\test_env1
    # Too difficult to get AppVeyor to handle Unicode directories
    - conda env create -f conda-recipe\testenv2.yaml -p %MINICONDA%\envs\test_env2
    - conda info -a

# Skip .NET project specific build phase.
build: off

test_script:
    - conda build conda-recipe --python=%PYTHON_VERSION%

deploy_script:
    - if not "%CONDA_SPEC%" == "" exit 0
    - if not "%APPVEYOR_REPO_BRANCH%" == "master" exit 0
    # Untagged builds uploaded to dev; tagged builds to main
    - if "%APPVEYOR_REPO_TAG%" == "false" set ANACONDA_LABEL=dev
    - if "%APPVEYOR_REPO_TAG%" == "true" set ANACONDA_LABEL=main
    - anaconda --verbose --token %ANACONDA_TOKEN% upload %MINICONDA%\conda-bld\*\*.tar.bz2 --user jupycon --force --label %ANACONDA_LABEL%
