environment:
  global:
    PYTHONUNBUFFERED: 1
    SKIP_NPM_TESTS: 1
  matrix:
    - MINICONDA: "C:\\Miniconda3-x64"
      PYTHON_VERSION: "3.6"
    - MINICONDA: "C:\\Miniconda3-x64"
      PYTHON_VERSION: "3.5"
    - MINICONDA: "C:\\Miniconda3-x64"
      PYTHON_VERSION: "2.7"
    - MINICONDA: "C:\\Miniconda35-x64"
      PYTHON_VERSION: "3.5"
      CONDA_SPEC: "=4.3"

install:
    # Because the specifics of activation need to be tested here, we are
    # fixing the version of conda *before* doing the full activation.
    - call %MINICONDA%\Scripts\conda install conda%CONDA_SPEC% --yes
    - call %MINICONDA%\Scripts\activate.bat
    - conda config --set always_yes yes --set changeps1 no --set auto_update_conda no --set safety_checks disabled
    # The tests need to see the Python kernel in the root environment
    - conda install conda-build ipykernel
    # The tests also need to see R and Python kernels in other environments.
    - conda create -n test_env1 r-irkernel r-base python=3
    - conda create -n test_env2 ipykernel python=2
    - conda info -a

# Skip .NET project specific build phase.
build: off
skip_branch_with_pr: true

test_script:
    - conda-build conda-recipe --python=%PYTHON_VERSION%
    - if %ERRORLEVEL% neq 0 exit 1
